from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from sqlalchemy import func
from datetime import datetime, timedelta
from app.database import get_db
from app.schemas.analytics import AnalyticsReport
from app.models.feedback import Feedback
from app.models.admin import Admin
from app.utils.dependencies import get_current_admin
import csv
import io
import json
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/analytics", tags=["analytics"])


@router.get("/reports", response_model=AnalyticsReport)
def get_analytics_report(
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin)
):
    """
    Get analytics report (Protected - Admin only)
    
    Returns:
    - Total feedbacks count
    - Overall average rating
    - Average ratings for last 30, 60, 90 days
    - Rating distribution (1-5)
    """
    from datetime import timezone
    now = datetime.now(timezone.utc)
    
    # Total feedbacks
    total_feedbacks = db.query(func.count(Feedback.id)).scalar()
    
    # Overall average rating
    overall_avg = db.query(func.avg(Feedback.rating)).scalar() or 0.0
    
    # Average rating last 30 days
    date_30_days_ago = now - timedelta(days=30)
    avg_30_days = db.query(func.avg(Feedback.rating)).filter(
        Feedback.created_at >= date_30_days_ago
    ).scalar() or 0.0
    
    # Average rating last 60 days
    date_60_days_ago = now - timedelta(days=60)
    avg_60_days = db.query(func.avg(Feedback.rating)).filter(
        Feedback.created_at >= date_60_days_ago
    ).scalar() or 0.0
    
    # Average rating last 90 days
    date_90_days_ago = now - timedelta(days=90)
    avg_90_days = db.query(func.avg(Feedback.rating)).filter(
        Feedback.created_at >= date_90_days_ago
    ).scalar() or 0.0
    
    # Rating distribution (count of each rating 1-5)
    rating_distribution = {}
    unique_ratings_count = 0
    for rating in range(1, 6):
        count = db.query(func.count(Feedback.id)).filter(
            Feedback.rating == rating
        ).scalar()
        rating_distribution[str(rating)] = count
        if count > 0:
            unique_ratings_count += 1
    
    logger.info(f"Analytics report generated by admin: {current_admin.username}")
    
    return {
        "total_feedbacks": total_feedbacks,
        "overall_avg_rating": round(overall_avg, 2),
        "avg_rating_last_30_days": round(avg_30_days, 2),
        "avg_rating_last_60_days": round(avg_60_days, 2),
        "avg_rating_last_90_days": round(avg_90_days, 2),
        "rating_distribution": rating_distribution,
        "unique_ratings": unique_ratings_count
    }


@router.get("/download")
def download_report(
    format: str = Query("csv", regex="^(csv|json)$"),
    db: Session = Depends(get_db),
    current_admin: Admin = Depends(get_current_admin)
):
    """
    Download feedback report (Protected - Admin only)
    
    Formats:
    - csv: CSV file
    - json: JSON file
    """
    # Get all feedbacks
    feedbacks = db.query(Feedback).order_by(Feedback.created_at.desc()).all()
    
    if format == "csv":
        # Generate CSV
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow([
            "ID", "Name", "Email", "Rating", "Description", 
            "Screenshot URL", "Client IP", "Created At"
        ])
        
        # Data rows
        for feedback in feedbacks:
            writer.writerow([
                feedback.id,
                feedback.name,
                feedback.email,
                feedback.rating,
                feedback.description or "",
                feedback.screenshot_url or "",
                feedback.client_ip or "",
                feedback.created_at.isoformat()
            ])
        
        output.seek(0)
        
        logger.info(f"CSV report downloaded by admin: {current_admin.username}")
        
        return StreamingResponse(
            iter([output.getvalue()]),
            media_type="text/csv",
            headers={"Content-Disposition": "attachment; filename=feedbacks.csv"}
        )
    
    else:  # json
        # Generate JSON
        data = []
        for feedback in feedbacks:
            data.append({
                "id": feedback.id,
                "name": feedback.name,
                "email": feedback.email,
                "rating": feedback.rating,
                "description": feedback.description,
                "screenshot_url": feedback.screenshot_url,
                "client_ip": feedback.client_ip,
                "created_at": feedback.created_at.isoformat()
            })
        
        json_data = json.dumps(data, indent=2)
        
        logger.info(f"JSON report downloaded by admin: {current_admin.username}")
        
        return StreamingResponse(
            iter([json_data]),
            media_type="application/json",
            headers={"Content-Disposition": "attachment; filename=feedbacks.json"}
        )
